apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fetch-capm-csv-data-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Tutorial for fetch CAPM CSV data"
    scenarios.ai.sap.com/name: "Fetch CAPM CSV Data"
    executables.ai.sap.com/description: "Get CAPM CSV Data"
    executables.ai.sap.com/name: "CAPM CSV Data"
  labels:
    scenarios.ai.sap.com/id: "CAPM-CSV-data"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
  - name: aitutorialrepo # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    container:
      image: docker.io/priya049/capm-csv:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/capm-csv.py"
